app/urls.py
from django.urls import path
from django.urls import re_path
from django.conf import settings
from django.views.static import serve
from . import views

from .views import mahasiswa_report_view,PendaftaranJson
from django.contrib.auth.views import LoginView
urlpatterns =[

    path('', views.login_view, name='login'),
    # path('', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('profil/',views.profil,name='profil'),
    path('logout/', views.logout_view, name='logout'),

    path('register', views.registerPengelola, name='registerPengelola'),

    path('log',views.log,name='log'),

    path('mahasiswa-report/', mahasiswa_report_view, name='mahasiswa_report'),
     path('pendaftaran/json', PendaftaranJson.as_view(), name='pendaftaran_json'),

    path('mahasiswa',views.indexMahasiswa,name='mahasiswa'),
    path('tambahMahasiswa',views.tambahMahasiswa,name='tambahMahasiswa'),
    path('postMahasiswa',views.postMahasiswa,name='postMahasiswa'),
    path('updateMahasiswa/<str:nim>',views.updateMahasiswa,name='updateMahasiswa'),
    path('postUpdateMahasiswa',views.postUpdateMahasiswa,name='postUpdateMahasiswa'),
    path('hapusMahasiswa/<str:nim>',views.hapusMahasiswa,name='hapusMahasiswa'),
    path('postHapusMahasiswa/<str:nim>',views.postHapusMahasiswa,name='postHapusMahasiswa'),

    path('kamar',views.indexKamar,name='kamar'),
    path('tambahKamar',views.tambahKamar,name='tambahKamar'),
    path('postKamar',views.postKamar,name='postKamar'),
    path('updateKamar/<str:nomor_kamar>',views.updateKamar,name='updateKamar'),
    path('postUpdateKamar',views.postUpdateKamar,name='postUpdateKamar'),
    path('hapusKamar/<str:nomor_kamar>',views.hapusKamar,name='hapusKamar'),
    path('postHapusKamar/<str:nomor_kamar>',views.postHapusKamar,name='postHapusKamar'),

    path('pengelola',views.indexPengelola,name='pengelola'),
    path('tambahPengelola',views.tambahPengelola,name='tambahPengelola'),
    path('postPengelola',views.postPengelola,name='postPengelola'),

    path('updatePengelola',views.updatePengelola,name='updatePengelola'),

    path('postUpdatePengelola',views.postUpdatePengelola,name='postUpdatePengelola'),
    path('hapusPengelola/<int:id_pengelola>',views.hapusPengelola,name='hapusPengelola'),
    path('postHapusPengelola/<int:id_pengelola>',views.postHapusPengelola,name='postHapusPengelola'),

    path('pendaftaran',views.indexPendaftaran,name='pendaftaran'),
    path('updatePendaftaran/<str:id_pendaftaran>',views.updatePendaftaran,name='updatePendaftaran'),
    path('postUpdatePendaftaran',views.postUpdatePendaftaran,name='postUpdatePendaftaran'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
     path('upload-image', views.upload_image, name='upload_image'),
    ]

percobaan3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
import datetime
# Create your models here.



class Kamars(models.Model):
    PILIHAN_KAMAR = (('TERSEDIA', 'Tersedia'), ('TERPAKAI', 'Terpakai'))

    nomor_kamar = models.IntegerField(primary_key=True, auto_created=True)
    status_kamar = models.CharField(
        max_length=8, choices=PILIHAN_KAMAR, default='Tersedia')
    nim = models.OneToOneField(
        'Mahasiswas', on_delete=models.SET_NULL, null=True, blank=True)

class Mahasiswas(models.Model):

    PILIHAN_JURUSAN = (
        ("Informatika", "Informatika"),
        ("Manajemen", "Manajemen"),
        ("Farmasi", "Farmasi"),
        ("Pendidikan Agama Kristen","Pendidikan Agama Kristen"),
        ("Fisika","Fisika"),
        ("Teologi Konseling Kristen","Teologi Konseling Kristen"),
        ("Akuntansi","Akuntansi"),
        ("Teknik Sipil","Teknik Sipil"),
        ("Musik Gereja","Musik Gereja"),
    )

    PILIHAN_PEMBAYARAN = (
        ("Qris", "Qris"),
        ("Cash", "Cash")
    )

    nim = models.CharField(max_length=10, primary_key=True)
    nama = models.CharField(max_length=255)
    jurusan = models.CharField(max_length=50,
                               choices=PILIHAN_JURUSAN,
                               default="Farmasi")
    no_telepon = models.CharField(max_length=20)
    tempat_lahir = models.CharField(max_length=255, default=None)
    tanggal_lahir = models.DateField(default=datetime.date.today)
    nomor_kamar = models.ForeignKey(
        Kamars, on_delete=models.SET_NULL, null=True, blank=True)

class Pengelolas(models.Model):
    pilihan_jk = (
        ("Laki-laki", "laki-laki"),
        ("Perempuan", "perempuan")
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True)
    nama = models.CharField(max_length=255,null=True)
    nik = models.CharField(max_length=20,null=True)
    jenis_kelamin = models.CharField(max_length=20,choices = pilihan_jk,default=None,null=True)
    tempat_lahir = models.CharField(max_length=255,null=True,blank=True)
    tanggal_lahir = models.DateField(default=None,null=True,blank=True)
    alamat = models.TextField(max_length=255,null=True)
    no_telepon = models.CharField(max_length=15,null=True)

class Pendaftarans(models.Model):
    id_pendaftaran = models.AutoField(primary_key=True)
    tanggal_daftar = models.DateField(default=datetime.date.today)
    tanggal_masuk = models.DateField(default=None, null=True, blank=True)
    tanggal_keluar = models.DateField(default=None, null=True, blank=True)
    bukti_bayar = models.ImageField(upload_to='bukti_bayar/',blank=True)
    nim = models.ForeignKey(Mahasiswas, on_delete=models.CASCADE)
    pengelola = models.ForeignKey(Pengelolas, on_delete=models.CASCADE, null=True, blank=True)

templates/kamar/formDelete.html
{% extends 'dashboard.html' %}
{% block title %}Hapus Kamar{% endblock %}
{% block content %}
<div class="card">
    <div class="card-body">
        <form method="POST" action="{% url 'postHapusKamar' data_kamar.nomor_kamar %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="">Nomor Kamar</label>
                <input class="form-control " readonly value="{{data_kamar.nomor_kamar}}" type="text"
                    name="nomor_kamar" id="nomor_kamar" />
            </div>
            <div class="form-group">
                <label for="">Status Kamar</label>
                <input class="form-control " readonly value="{{data_kamar.status_kamar}}" type="text"
                    name="status_kamar" id="status_kamar" />
            </div>

            <button class="btn btn-primary" type="button" onclick="location.href='{% url 'kamar' %}'"><i
                    class="fas fa-angle-left"></i> Kembali</button>
            <button class="btn btn-danger" type="submit">
                <i class="fa fa-save"></i> Hapus
            </button>
        </form>

    </div>
</div>
{% endblock %}

templates/kamar/formTambah.html
{% extends 'dashboard.html' %}
{% block title %}Tambah Kamar{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <form method="POST" action="{% url 'postKamar' %}">
                 {% csrf_token %}
                <div class="form-group">
                    <label for="">Nomor Kamar</label>
                    <input class="form-control " value="" type="text"
                        name="nomor_kamar" id="nomor_kamar" />
                </div> 

                <div class="form-group">
                    <label for="">Status Kamar</label>
                    <select class="form-control"
                    name="status_kamar" id="status_kamar" >
                        <option value="" disabled selected>Status Kamar</option>
                        {% for status in data_kamar.PILIHAN_KAMAR %}
                            <option value="{{ status.0 }}">{{ status.1 }}</option>
                        {% endfor %}
                    </select>
                </div>

                <button class="btn btn-primary" type="button" onclick="location.href='{% url 'kamar' %}'"><i class="fas fa-angle-left"></i> Kembali</button>
                <button class="btn btn-success" type="submit">
                    <i class="fa fa-save"></i> Simpan
                </button>
            </form>
        </div>
    </div>
{% endblock %}

templates/kamar/formUpdate.html
{% extends 'dashboard.html' %}
{% block title %}Update Kamar{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <form method="POST" action="{% url 'postUpdateKamar' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="">Nomor Kamar</label>
                    <input class="form-control" readonly value="{{ data_kamar.nomor_kamar }}" type="text"
                        name="nomor_kamar" id="nomor_kamar" />
                </div>
                <div class="form-group">
                    <label for="">Mahasiswa yang menempati</label>
                    <select class="form-control" name="mahasiswa" id="mahasiswa">
                        <option value="">None</option>
                        {% for mahasiswa in all_mahasiswa %}
                            <option value="{{ mahasiswa.nim }}" {% if data_mahasiswa and data_mahasiswa.nim == mahasiswa.nim %}selected{% endif %}>{{ mahasiswa.nama }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <button class="btn btn-primary" type="button" onclick="location.href='{% url 'kamar' %}'">
                    <i class="fas fa-angle-left"></i> Kembali
                </button>
                <button class="btn btn-success" type="submit">
                    <i class="fa fa-save"></i> Simpan
                </button>
            </form>
        </div>
    </div>
{% endblock %}

templates/kamar/index.html
{% extends 'dashboard.html' %}
{% block title %}Data Kamar{% endblock %}
{% block content %}
<h1 class="title">Data Kamar</h1>
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% comment %} <a class="btn btn-success mb-2" href="{% url 'postKamar' %}"><i class="fa fa-save"></i> Tambah Kamar</a> {% endcomment %}
    


    <div class="card">
      
        <div class="card-body">
            <table class="table " id="example" width='100%'>
                <thead >
                    <tr>
                        <th>Nomor Kamar</th>
                        <th>Status Kamar</th>
                        <th>Ditempati</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for kamar in data_kamar %}
                        <tr>
                            <td>{{ kamar.nomor_kamar }}</td>
                            <td>
                                {% if kamar.status_kamar == 'Tersedia' %}
                                    Tersedia
                                {% else %}
                                    Terpakai
                                {% endif %}
                            </td>
                            <td>
                              {% if kamar.mahasiswas_set.all %}
                                  {% for mahasiswa in kamar.mahasiswas_set.all %}
                                      <p>{{ mahasiswa.nama }} | {{ mahasiswa.nim }}</p>
                                  {% endfor %}
                              {% else %}
                                  <p>-</p>
                              {% endif %}
                          </td>
                            <td>
                                <a class="btn btn-info"
                                   href="{% url 'updateKamar' kamar.nomor_kamar %}"><i class="fas fa-edit"></i>Edit</a>
                            </td>
                        </tr>
                        {% empty %}
                            <tr>
                                <td style="text-align: center;" colspan="4"><b>Data Kosong</b></td>
                            </tr>
                    {% endfor %}
                            
                    </tbody>
                </table>
            </div>
            
        </div>

        <script>
            $(document).ready(function() {
              var table = $('#example').DataTable({
                dom: 'Bfrtip',
                buttons: [
                  {
                    extend: 'pdf',
                    text: 'PDF',
                    title: 'Data Kamar',
                    customize: function(doc) {
                      doc.defaultFileName = 'data_kamar';
                      // Remove the "Aksi" column from the PDF document
                      doc.content[1].table.body.forEach(function(row) {
                        row.splice(3, 1); // Remove the "Aksi" column (index 3)
                      });
                    }
                  }
                ]
              });
          
              $('#example thead th').each(function(index) {
                var column = table.column($(this));
                var columnHeader = $(this);
          
                if (columnHeader.data('searchable') !== false) {
                  columnHeader.on('click', function() {
                    if (!columnHeader.hasClass('sorting_disabled')) {
                      if (columnHeader.hasClass('filtering')) {
                        column.search('').draw();
                        columnHeader.removeClass('filtering');
                      } else {
                        columnHeader.addClass('filtering');
                      }
                    }
                  });
          
                  if (index !== 3) { // Exclude the "Aksi" column (index 3) from searching
                    var input = $('<input type="text" class="form-control form-control-sm" placeholder="Search">')
                      .appendTo(columnHeader)
                      .on('keyup change clear', function() {
                        if (column.search() !== this.value) {
                          column.search(this.value).draw();
                        }
                      });
          
                    columnHeader.wrapInner('<span class="filterable"></span>');
                  }
                }
              });
            });
          </script>
          

    {% endblock %}